version: '3.9'

services:
  nginx:
    ports:
      - "82:82"
    volumes:
      - ./nginx/nginx.conf.development:/etc/nginx/conf.d/nginx.conf

  server:
    build:
      target: development
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
      - redis

  client:
    build:
      target: development
    volumes:
      - ./client/src:/app/src
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true

  db:
    container_name: youtube-api-db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - youtube-api-network
  
  dbadmin:
    container_name: youtube-api-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    networks:
      - youtube-api-network

  redis:
    ports:
      - 6379:6379

  redis-commander:
    container_name: youtube-api-redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "5051:8081"
    networks:
      - youtube-api-network