version: '3.9'

services:
  nginx:
    ports:
      - "81:81"
    volumes:
      - ./nginx/nginx.conf.development:/etc/nginx/conf.d/nginx.conf

  server:
    build:
      target: development
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db

  client:
    build:
      target: development
    volumes:
      - ./client/src:/app/src
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true

  db:
    container_name: youtube-api-dev-db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - youtube-api-network
  
  dbadmin:
    container_name: youtube-api-dev-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    networks:
      - youtube-api-network