version: '3.9'

services:
  nginx:
    ports:
      - "10000:10000"
    volumes:
      - ./nginx/nginx.conf.production:/etc/nginx/conf.d/nginx.conf

  server:
    build:
      target: production
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db

  client:
    build:
      target: production
    volumes:
      - ./client/src:/app/src