version: "3.9"

services:
  nginx:
    container_name: youtube-api-nginx
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - client
      - server
    networks:
      - youtube-api-network
      - youtube-api-external

  server:
    container_name: youtube-api-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - youtube-api-network
      - youtube-api-external

  client:
    container_name: youtube-api-client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - youtube-api-network

  redis:
    container_name: youtube-api-redis
    image: redis:6.2-alpine
    restart: always
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--bind",
        "redis",
        "--port",
        "6379",
      ]
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - youtube-api-network

networks:
  youtube-api-network:
    driver: bridge
    name: youtube-api-network
  youtube-api-external:
    external: 
      name: youtube-api-external
