version: "3.9"

services:
  nginx:
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.conf.development:/etc/nginx/conf.d/nginx.conf
    networks:
      - youtube-api-network
      - youtube-api-external

  server:
    build:
      target: development
    volumes:
      - ./server/src:/app/src
    depends_on:
      - redis
    networks:
      - postgres

  client:
    build:
      target: development
    volumes:
      - ./client/src:/app/src
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true

  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redis-commander:
    container_name: youtube-api-redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    networks:
      - youtube-api-network

networks:
  youtube-api-network:
    driver: bridge
  youtube-api-external:
    name: youtube-api-external
  postgres:
    name: postgres_postgres
    external: true
