version: '3.9'

services:
  nginx:
    container_name: youtube-api-nginx
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - client
      - server
    networks:
      - youtube-api-network

  server:
    container_name: youtube-api-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - youtube-api-network

  client:
    container_name: youtube-api-client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - youtube-api-network

networks:
  youtube-api-network:
    driver: bridge