version: '3.9'

services:
  nginx:
    ports:
      - "81:81"
    volumes:
      - ./nginx/nginx.conf.production:/etc/nginx/conf.d/nginx.conf

  server:
    build:
      target: production
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db

  client:
    build:
      target: production
    volumes:
      - ./client/src:/app/src
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true