version: '3.9'

services:
  # server:
    # build:
      # context: ./server
      # dockerfile: Dockerfile
      # target: dev
    # ports:
      # - 5000:5000
    # volumes:
      # - ./src:/app/src
    # depends_on:
      # - db

  client:
    container_name: youtube-api-client
    command: npm run start-watch
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./client/src:/app/src:delegated"
    restart: always
    stdin_open: true
    tty: true

  # db:
    # image: postgres:14-alpine
    # restart: always
    # ports:
      # - 5433:5432
    # environment:
      # POSTGRES_PASSWORD: postgres
  
  # dbadmin:
    # image: dpage/pgadmin4
    # restart: always
    # ports:
      # - 5050:80
    # environment:
      # PGADMIN_DEFAULT_EMAIL: admin@admin.com
      # PGADMIN_DEFAULT_PASSWORD: pgadmin4

  